// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0M5L6hKK9hP5u6RP3EL-UxzA77Psa-5Q',
    appId: '1:544626766506:web:acffc95c1570391ab9d6d3',
    messagingSenderId: '544626766506',
    projectId: 'finalyearprojec-80025',
    authDomain: 'finalyearprojec-80025.firebaseapp.com',
    storageBucket: 'finalyearprojec-80025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM52Ts6Gnz0IJOMIQCV9nw-4MS_oHNH3M',
    appId: '1:544626766506:android:6f056c7997f7e71bb9d6d3',
    messagingSenderId: '544626766506',
    projectId: 'finalyearprojec-80025',
    storageBucket: 'finalyearprojec-80025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVa1fkoq_nDZFGjym1YNYJlWMhFxvNrMk',
    appId: '1:544626766506:ios:0c184c28316f4d8bb9d6d3',
    messagingSenderId: '544626766506',
    projectId: 'finalyearprojec-80025',
    storageBucket: 'finalyearprojec-80025.appspot.com',
    iosBundleId: 'com.example.coincontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVa1fkoq_nDZFGjym1YNYJlWMhFxvNrMk',
    appId: '1:544626766506:ios:0c184c28316f4d8bb9d6d3',
    messagingSenderId: '544626766506',
    projectId: 'finalyearprojec-80025',
    storageBucket: 'finalyearprojec-80025.appspot.com',
    iosBundleId: 'com.example.coincontrol',
  );
}
